fixed menu
bastakom/peter-liljeroth pull request #2
Opened 2024-12-18 15:35 UTC by andjan3

2024-12-19 13:31 UTC, bastakom commented on .gitignore
remove line

2024-12-19 13:36 UTC, andjan3 commented on .gitignore
Fixat!

2024-12-19 13:37 UTC, bastakom requested changes

2024-12-19 13:37 UTC, bastakom commented on components/ui/nav/nav.tsx
> +    Menu: LinkItem[];
Use small letters for data

2024-12-19 13:37 UTC, bastakom commented on package-lock.json
Remove package-lock.json

2024-12-19 13:46 UTC, andjan3 commented on components/ui/nav/nav.tsx
> +    Menu: LinkItem[];
Changed to camelCase, or did you mean to change it to all lowercase instead?

2024-12-20 11:16 UTC, bastakom approved these changes

2024-12-20 11:16 UTC, merged